local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, {})
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<leader>ps', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") });
end)
vim.api.nvim_set_keymap('n', '<Leader>ph', ':lua require"telescope.builtin".find_files({ hidden = true })<CR>', {noremap = true, silent = true})

local function create_codecompanion_workspace()
  local input = vim.fn.input("Workspace Name: ")

  if input == "" then
    print("Cancelled.")
    return
  end

  local workspace = {
    workspace = {
      name = input,
      description = "Generated by Telescope prompt",
    }
  }

  local json = vim.fn.json_encode(workspace)
  local path = vim.fn.getcwd() .. "/codecompanion-workspace.json"

  local file = io.open(path, "w")
  if file then
    file:write(json)
    file:close()
    print("Workspace file created at: " .. path)
  else
    print("Failed to create workspace file.")
  end
end
require('telescope').setup{
  extensions = {
    codecompanion = {
      create_workspace = create_codecompanion_workspace
    }
  }
}

vim.api.nvim_create_user_command("CodeCompanionCreateWorkspace", create_codecompanion_workspace, {})


